# OpenAI and Model constants
AZURE_OPENAI_API_KEY = ""
AZURE_OPENAI_ENDPOINT = ""

GPT_DEPLOYMENT = ""
GPT_VERSION = ""
DALLE_DEPLOYMENT = ""
DALLE_VERSION = ""
WHISPER_DEPLOYMENT = ""
WHISPER_VERSION = ""
